CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO





CREATE TABLE CLINICA (
 idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeEmpresa VARCHAR(20)
);
GO

CREATE TABLE DONO (
 idDono TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeDono VARCHAR(20)
);
GO

CREATE TABLE TIPO_PET (
 idTipoPet TINYINT PRIMARY KEY IDENTITY(1,1),
 descricaoTipo VARCHAR(20)
);
GO





CREATE TABLE VETERINARIO (
 idVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
 idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
 nomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE RACA (
 idRaca TINYINT PRIMARY KEY IDENTITY(1,1),
 idTipoPet TINYINT FOREIGN KEY REFERENCES TIPO_PET(idTipoPet),
 nomeRaca VARCHAR(20)
);
GO

CREATE TABLE PET (
 idPet TINYINT PRIMARY KEY IDENTITY(1,1),
 idDono TINYINT FOREIGN KEY REFERENCES DONO(idDono),
 idRaca TINYINT FOREIGN KEY REFERENCES RACA(idRaca),
 nomePet VARCHAR(20)
);
GO

CREATE TABLE ATENDIMENTO (
 idAtendimento TINYINT PRIMARY KEY IDENTITY(1,1),
 idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
 idPet TINYINT FOREIGN KEY REFERENCES PET(idPet),
 dataAtendimento SMALLDATETIME
);
GO