CREATE DATABASE inlock_games_tarde;
GO

USE inlock_games_tarde;
GO

CREATE TABLE ESTUDIOS
(
idEstudio SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeEstudio VARCHAR (80) NOT NULL
);
GO

CREATE TABLE JOGOS
(
idJogo INT PRIMARY KEY IDENTITY (1,1),
nomeJogo VARCHAR (80) NOT NULL,
descricao VARCHAR (300) NOT NULL,
dataLancamento DATE NOT NULL,
idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIOS(idEstudio),
valor MONEY NOT NULL
);
GO

CREATE TABLE TIPOUSUARIO
(
idTipoUsuario TINYINT PRIMARY KEY IDENTITY (1,1),
titulo VARCHAR (15) NOT NULL
);
GO

CREATE TABLE USUARIOS
(
idUsuario INT PRIMARY KEY IDENTITY (1,1),
email VARCHAR (256) UNIQUE NOT NULL,
senha VARCHAR (256) NOT NULL,
idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario)
);
GO