CREATE DATABASE OPTUS_S;
GO

USE OPTUS_S;
GO


CREATE TABLE USUARIO (
 idUsuario TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeUsuario VARCHAR(20),
 emailUsuario VARCHAR(20),
 senhaUsuario VARCHAR(20)
);
GO

CREATE TABLE ARTISTA (
 idArtista TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeArtista VARCHAR(20)
);
GO

CREATE TABLE ESTILO (
 idEstilo TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeEstilo VARCHAR(20)
);
GO

CREATE TABLE ALBUM (
 idAlbum TINYINT PRIMARY KEY IDENTITY(1,1),
 idArtista TINYINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
 nomeAlbum VARCHAR(20)
);
GO

CREATE TABLE ALBUM_ESTILO (
 idAlbum_estilo TINYINT PRIMARY KEY IDENTITY(1,1),
 idAlbum TINYINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
 idEstilo TINYINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
 codAlbumEstilo VARCHAR(20)
);
GO